name: Auto Tag Backend Common
on:
  push:
    branches:
      - main
jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Minor version for each merge
        id: AutoTagger
        uses: anothrNick/github-tag-action@v1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true